"""Ops Mission Control — incident store and dispatch index.

The dispatch index (``incidents/index.json``) is the claim ledger: it is what
makes a firing signal *owned* rather than merely visible. Two properties matter
and are enforced here rather than by convention:

**Claims are atomic.** Two heartbeats (two KiroCrew instances, or an overlapping
tick) must never both claim the same signal and spawn two investigations of one
incident. ``claim`` takes an exclusive file lock and does a compare-and-set, so
exactly one caller wins and the loser skips.

**Transitions are legal or refused.** An incident cannot jump from ``unclaimed``
straight to ``resolved`` — that would let the board assert work was done that no
investigation ever ran. ``models.LEGAL_TRANSITIONS`` is the whole grammar and
``transition`` is the only door.

File locking goes through ``platform_compat`` (never raw ``fcntl``) because this
app must work on Windows, where that module does not exist.

See ``docs/task-specs/2026/07/ops-mission-control/spec.md`` §3, §4.5.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any

from kiro_crew import platform_compat
from kiro_crew.apps.builtins.ops_mission_control.backend.models import (
    LEGAL_TRANSITIONS,
    OPEN_STATUSES,
    STATUS_DISPATCHED,
    STATUS_INVESTIGATING,
    STATUS_STALE,
    TERMINAL_STATUSES,
    Incident,
    Signal,
    utc_now_iso,
)
from kiro_crew.apps.manager import app_data_dir
from kiro_crew.atomic_write import atomic_write

logger = logging.getLogger(__name__)

APP_NAME = "ops-mission-control"

_INCIDENTS_DIRNAME = "incidents"
_INDEX_FILENAME = "index.json"
_LOCK_FILENAME = ".index.lock"

#: Incident id prefix. ``INV`` (investigation) rather than ``INC`` so it reads
#: distinctly from provider-native incident numbers in a Slack thread title.
_ID_PREFIX = "INV"

#: Directory mode for the incident tree. Not secret (no tokens live here — see
#: ``secrets.py``), but incident logs describe a user's production failures, so
#: owner-only is the right default.
_DIR_MODE = 0o700

#: Statuses the stale sweep can release. An incident that has been claimed but is
#: not progressing holds its signal unworked, and the failure is silent — so both
#: pre-terminal working states are sweepable.
_SWEEPABLE_STATUSES: frozenset[str] = frozenset({STATUS_DISPATCHED, STATUS_INVESTIGATING})


def incidents_dir() -> Path:
    d = app_data_dir(APP_NAME) / _INCIDENTS_DIRNAME
    d.mkdir(parents=True, exist_ok=True)
    platform_compat.chmod_safe(d, _DIR_MODE)
    return d


def index_path() -> Path:
    return incidents_dir() / _INDEX_FILENAME


def incident_log_path(incident_id: str) -> Path:
    """Markdown investigation log for one incident.

    ``incident_id`` is generated by this module (``INV-<n>``), never
    caller-supplied, but it lands in a filesystem path — so it is validated
    anyway rather than trusted, keeping the guarantee local to this function.
    """
    safe = "".join(c for c in incident_id if c.isalnum() or c in "-_")
    if not safe or safe != incident_id:
        raise ValueError(f"unsafe incident id: {incident_id!r}")
    return incidents_dir() / f"{safe}.md"


# ---------------------------------------------------------------------------
# Index I/O
# ---------------------------------------------------------------------------


def _read_index_unlocked() -> dict[str, Incident]:
    try:
        raw = json.loads(index_path().read_text(encoding="utf-8"))
    except (FileNotFoundError, OSError, json.JSONDecodeError):
        return {}
    if not isinstance(raw, dict):
        return {}
    out: dict[str, Incident] = {}
    for key, value in raw.items():
        if isinstance(value, dict):
            try:
                out[str(key)] = Incident.from_dict(value)
            except (TypeError, ValueError):
                logger.warning("ops-mission-control: skipping malformed index entry %r", key)
    return out


def _write_index_unlocked(index: dict[str, Incident]) -> None:
    payload = {key: inc.to_dict() for key, inc in index.items()}
    atomic_write(index_path(), json.dumps(payload, indent=2, sort_keys=True))


class _IndexLock:
    """Exclusive lock around a read-modify-write of the dispatch index.

    Routed through ``platform_compat.file_lock`` so the same code works on
    Windows, where ``fcntl`` does not exist.
    """

    def __init__(self) -> None:
        self._fd: int | None = None

    def __enter__(self) -> _IndexLock:
        lock_file = incidents_dir() / _LOCK_FILENAME
        self._fd = os.open(str(lock_file), os.O_CREAT | os.O_RDWR, 0o600)
        platform_compat.acquire_lock(self._fd, exclusive=True)
        return self

    def __exit__(self, *exc: object) -> None:
        if self._fd is not None:
            try:
                platform_compat.release_lock(self._fd)
            finally:
                os.close(self._fd)
                self._fd = None


def read_index() -> dict[str, Incident]:
    """Snapshot of the dispatch index. No lock — readers tolerate staleness."""
    return _read_index_unlocked()


def get_incident(incident_id: str) -> Incident | None:
    return read_index().get(incident_id)


def find_by_signal(signal_id: str) -> Incident | None:
    """Locate an incident by its originating signal id.

    The heartbeat uses this to decide "is this already claimed?", so it matches on
    ``Signal.id`` (provider-scoped and stable across polls) rather than on the
    incident id.
    """
    for inc in read_index().values():
        if inc.signal.id == signal_id:
            return inc
    return None


def _next_incident_id(index: dict[str, Incident]) -> str:
    highest = 0
    for key in index:
        if key.startswith(f"{_ID_PREFIX}-"):
            try:
                highest = max(highest, int(key.split("-", 1)[1]))
            except (IndexError, ValueError):
                continue
    return f"{_ID_PREFIX}-{highest + 1}"


# ---------------------------------------------------------------------------
# Claim + transition
# ---------------------------------------------------------------------------


def claim(signal: Signal, *, operating_mode: str) -> Incident | None:
    """Atomically claim ``signal``, returning the new incident or ``None``.

    ``None`` means someone else already owns this signal — the caller must skip
    it, NOT retry. This is the compare-and-set that prevents two heartbeats from
    spawning duplicate investigations of one alarm.

    A signal whose previous incident went ``stale`` is re-claimable: the stale
    incident is re-dispatched in place, keeping one timeline per signal rather
    than accumulating a new incident per re-pickup.

    **A signal whose previous incident reached a TERMINAL status is also
    re-claimable — as a NEW incident.** ``signal.id`` is stable for the life of the
    underlying alarm (``cloudwatch:alarm/DlqDepth`` forever), so treating "terminal"
    as "accounted for" meant the app permanently stopped responding to any failure it
    had already handled once. Proven: resolve an alarm on day 1, and its re-firing on
    days 2, 3, and 30 all returned ``None``. Worse, it made the app's whole premise
    unreachable — the compounding-memory fast path can only pay off on a SECOND
    occurrence, and a second occurrence could never be claimed.

    A recurrence is a new incident, not a reopening: the first one has its own
    diagnosis, resolution, and Slack thread, and overwriting those would destroy the
    record that makes the ledger trustworthy. Re-firing after a real fix is exactly
    the signal a responder most needs to see ("we fixed this and it came back").
    """
    with _IndexLock():
        index = _read_index_unlocked()

        for inc in index.values():
            if inc.signal.id != signal.id:
                continue
            if inc.status == STATUS_STALE:
                inc.status = STATUS_DISPATCHED
                inc.operating_mode = operating_mode
                inc.updated_at = utc_now_iso()
                # Refresh the signal snapshot: severity or resource may have
                # moved since the original claim.
                inc.signal = signal
                _write_index_unlocked(index)
                return inc
            if inc.status in TERMINAL_STATUSES:
                # Closed. This firing is a recurrence — fall through and open a new
                # incident rather than blocking forever on a finished one.
                continue
            # An OPEN incident owns this signal (dispatched / investigating /
            # needs_human). Losing that race is normal, not an error.
            return None

        incident_id = _next_incident_id(index)
        now = utc_now_iso()
        incident = Incident(
            incident_id=incident_id,
            signal=signal,
            status=STATUS_DISPATCHED,
            operating_mode=operating_mode,
            claimed_at=now,
            updated_at=now,
        )
        index[incident_id] = incident
        _write_index_unlocked(index)
        return incident


def transition(incident_id: str, new_status: str, **updates: Any) -> Incident:
    """Move an incident to ``new_status``, refusing illegal transitions.

    Raises ``KeyError`` for an unknown incident and ``ValueError`` for a
    transition the grammar does not allow. Extra keyword arguments update
    matching ``Incident`` fields in the same locked write, so a caller never has
    to do a second read-modify-write to attach a diagnosis or a slot key.
    """
    with _IndexLock():
        index = _read_index_unlocked()
        incident = index.get(incident_id)
        if incident is None:
            raise KeyError(incident_id)

        if new_status != incident.status:
            allowed = LEGAL_TRANSITIONS.get(incident.status, frozenset())
            if new_status not in allowed:
                raise ValueError(
                    f"illegal transition {incident.status!r} -> {new_status!r} "
                    f"for {incident_id}"
                )
            incident.status = new_status

        for key, value in updates.items():
            if hasattr(incident, key):
                setattr(incident, key, value)
            else:
                logger.warning("ops-mission-control: ignoring unknown field %r", key)

        incident.updated_at = utc_now_iso()
        index[incident_id] = incident
        _write_index_unlocked(index)
        return incident


def update_fields(incident_id: str, **updates: Any) -> Incident:
    """Update incident fields without changing status."""
    current = get_incident(incident_id)
    if current is None:
        raise KeyError(incident_id)
    return transition(incident_id, current.status, **updates)


def sweep_stale(stale_after_secs: int) -> list[str]:
    """Release incidents idle beyond ``stale_after_secs`` for re-pickup.

    Without this, an investigation whose agent died leaves a signal permanently
    claimed and therefore permanently unworked — the failure mode is silent, which
    is why the sweep runs on every heartbeat rather than on demand.
    """
    from datetime import datetime, timezone

    released: list[str] = []
    now = datetime.now(timezone.utc)
    with _IndexLock():
        index = _read_index_unlocked()
        changed = False
        for incident_id, inc in index.items():
            if inc.status not in _SWEEPABLE_STATUSES:
                continue
            try:
                seen = datetime.strptime(inc.updated_at, "%Y-%m-%dT%H:%M:%SZ").replace(
                    tzinfo=timezone.utc
                )
            except (TypeError, ValueError):
                continue
            if (now - seen).total_seconds() < stale_after_secs:
                continue
            if STATUS_STALE not in LEGAL_TRANSITIONS.get(inc.status, frozenset()):
                continue
            inc.status = STATUS_STALE
            inc.updated_at = utc_now_iso()
            released.append(incident_id)
            changed = True
        if changed:
            _write_index_unlocked(index)
    return released


def open_incidents() -> list[Incident]:
    """Incidents that represent live work, newest claim first."""
    return sorted(
        (inc for inc in read_index().values() if inc.status in OPEN_STATUSES),
        key=lambda i: i.claimed_at,
        reverse=True,
    )


def counts_by_status() -> dict[str, int]:
    counts: dict[str, int] = {}
    for inc in read_index().values():
        counts[inc.status] = counts.get(inc.status, 0) + 1
    return counts


#: Closed incidents kept in the dispatch index. Open ones are NEVER pruned regardless
#: of this cap — live work must not vanish because history is long.
#:
#: This exists because making a resolved alarm re-claimable (see ``claim``) removed the
#: accidental ceiling that "one incident per alarm, forever" used to provide. A genuinely
#: flapping alarm on the 2-minute dispatch cadence now mints a new incident per flap, and
#: every claim re-reads and re-writes the WHOLE index — measured superlinear: 50 entries
#: → 6ms/claim, 450 → 53ms. Left unbounded, a month of one flapping alarm projects to
#: ~21,600 incidents, and `/incidents` returns every one of them to the dashboard.
#:
#: 500 is chosen to be far above any real review window (a responder looks at this week,
#: not last quarter) while keeping claim cost flat and the board payload bounded. The
#: investigation LOGS are separate files and are deliberately left alone — pruning an
#: index row does not destroy the written record of what happened.
MAX_CLOSED_INCIDENTS = 500


def prune_closed(*, keep: int = MAX_CLOSED_INCIDENTS) -> int:
    """Drop the oldest closed incidents beyond ``keep``. Returns how many were removed.

    Runs from the daily hygiene pass, not from ``claim``: pruning is maintenance, and
    doing it on the hot path would make an ordinary claim occasionally pay for a large
    rewrite. Ordered by ``updated_at`` (when it CLOSED) rather than ``claimed_at``, so a
    long-running incident that just finished is treated as recent.
    """
    with _IndexLock():
        index = _read_index_unlocked()
        closed = [inc for inc in index.values() if inc.status in TERMINAL_STATUSES]
        if len(closed) <= keep:
            return 0
        closed.sort(key=lambda i: (i.updated_at, i.incident_id), reverse=True)
        for inc in closed[keep:]:
            del index[inc.incident_id]
        removed = len(closed) - keep
        _write_index_unlocked(index)
    logger.info("ops-mission-control: pruned %d closed incident(s) from the index", removed)
    return removed


# ---------------------------------------------------------------------------
# Investigation log
# ---------------------------------------------------------------------------


def write_log(incident: Incident, *, diagnosis: str, actions: str, next_steps: str) -> Path:
    """Write the human-readable investigation log.

    Markdown on disk rather than only JSON because these logs are the artifact a
    human reads at 2am, and the artifact a git-synced team diffs. The structure
    mirrors the internal system's per-ticket investigation files.
    """
    path = incident_log_path(incident.incident_id)
    body = f"""# {incident.incident_id} — {incident.signal.title}

| | |
|---|---|
| Signal | `{incident.signal.id}` |
| Source | {incident.signal.source} |
| Severity | {incident.signal.severity} |
| Resource | {incident.signal.resource or "—"} |
| Fired | {incident.signal.fired_at} |
| Status | {incident.status} |
| Mode | {incident.operating_mode} |
| Fingerprint | `{incident.signal.fingerprint}` |

## Diagnosis

{diagnosis or "_pending_"}

## Actions taken

{actions or "_none_"}

## Next steps

{next_steps or "_none_"}

## Matched knowledge

{chr(10).join(f"- `{m}`" for m in incident.ledger_matches) or "_no prior pattern matched_"}
"""
    atomic_write(path, body)
    return path


def read_log(incident_id: str) -> str:
    try:
        return incident_log_path(incident_id).read_text(encoding="utf-8")
    except (FileNotFoundError, OSError, ValueError):
        return ""
